### ISSUE TITLE
Duplication of survey results during upload problem

### ISSUE THREAD

**Issue by RKnepper3** [Esri/Survey123Community#389] opened 2016-03-24 14:03 UTC
Ok so we finally had a project kickoff and went out in the field to do an entire day of real work collection.  The survey collection in the field went very smooth and Survey123 was great.  Due to connectivity issues and the fact that we don't want to require our field staff to use their own data plans we did not upload surveys in the field, we simply saved them then uploaded when we returned home.  I had 2 field staff working.

1 collected 27 surveys with about 140 pictures, he was at home on decent wireless and took about 30 minutes to collect data which had some of the surveys fail to upload which required 2-4 retries.  I collected 28 with about 150 pictures,  I was on slower hotel wireless which took about 2 hours to upload my photos and also have several fail requiring 2-4 retries.

I can live with that but my issue is that this morning I went in to review the uploaded data.  I found that many records were duplicated.  The first staff shows 31 records were uploaded instead of 27 and I show 42 instead of 28.  I looked over the data and from creation times I can find the duplicate records.  This is a major concern in fully deploying Survey123.  Any ideas on how to avoid this?  I am assuming the failed uploads then resubmitting was the cause.

**Comment by RKnepper3** [comment] 2016-03-24 14:29
And I take back that I can easily find the duplicates.  I am running through the data now and it is very off.

**Comment by RKnepper3** [comment] 2016-03-24 15:00
I did find that all 55 separate inspections were uploaded, just with duplications.  I looked at one of the sites duplicated.  It seems that 1 upload included all the photos and the 2nd only had some of the photos.  It seems that if the attributes uploaded it saved it but marked it as failed since all the photos did not.  Then one the upload was attempted again it also saved it.  If all the photos uploaded it marked it as complete.

**Comment by bowlesgsrcx** [comment] 2016-03-24 17:18
What version of the App and Connect are you using?

**Comment by RKnepper3** [comment] 2016-03-25 15:38
Sorry, I was out yesterday.  I talked to Ismael yesterday and it seems to be related to my survey size having 5-7 photos (large) and slow internet and is a known issue being worked on (I bielve he said error 400).  I am using the current versions of both

**Comment by survey123** [comment] 2016-03-31 22:39
Hi. We have been working on this in the past few weeks. We believe we have a fix in place and will be making it available around mid April with the International Children's Book Release. We will need to keep a good eye on this one, as the issue is caused by multiple factors. Thanks Ron for helping us test this as well!

@RKnepper3 
@bowlesgsrcx

**Comment by survey123** [comment] 2016-04-11 22:57
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)

**Closed by survey123** 2016-04-11 22:57 UTC
Labels: Status - Fixed
