### ISSUE TITLE
Androis: Using "pick a photo" options should display the photo gallery not the default file system.

### ISSUE THREAD

**Issue by ssylvia** [Esri/Survey123Community#176] opened 2015-09-16 17:36 UTC

**Comment by survey123** [comment] 2015-09-16 20:06
Thanks Stephen for your feedback. We are planning to have this fixed in our next update. This is a duplicate of #141   Hoping to have this ready to go for the October 1st update.

**Comment by survey123** [comment] 2015-09-24 22:52
Fixed on build 1.1.4. Closing.
@ssylvia

**Closed by survey123** 2015-09-24 22:52 UTC
Labels: Status - Fixed, Survey123 App, Type - Duplicate
