### ISSUE TITLE
v1.4.28 will not submit or save survey

### ISSUE THREAD

**Issue by abrazell** [Esri/Survey123Community#463] opened 2016-05-17 19:05 UTC
I am attempting to submit a survey.  After clicking the check button in the lower right corner, nothing happens.  I am also unable to save drafts.  Any assistance is great appreciated.

**Comment by survey123** [comment] 2016-05-17 23:31
HI. What device are you using?

**Comment by chrislesueur** [comment] 2016-05-18 07:34
I had the same experience at a Survey123 workshop (May 11th 2016), several students in the class downloaded and completed the Survey but the app would not let them submit. This happened on both iOS and Android.

**Comment by survey123** [comment] 2016-07-26 07:41
@abrazell @chrislesueur 
It looks like this issue is being caused by an incorrect Instance_Name expression in your Survey.
We will improve error handling in our next update to Survey123. Easy fix, but took us forever to find the source of the problem. Thanks for reporting.

In the meantime, please review your Instance_Name expression for errors.

**Comment by survey123** [comment] 2016-09-01 17:00
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17

**Closed by survey123** 2016-09-01 17:00 UTC
Labels: Status - Fixed, Survey123 App, Type - Bug
