### ISSUE TITLE
The drop-down list from ‘select_multiple’ type doesn’t work on iOS and Android apps

### ISSUE THREAD

**Issue by esri4591** [Esri/Survey123Community#123] opened 2015-06-22 07:48 UTC
The drop-down list from ‘select_multiple’ type doesn’t work on iOS and Android apps
(But in Windows App, it works fine.)

![survey123_mobileapps png](https://cloud.githubusercontent.com/assets/4626334/8277440/fe47434e-18ec-11e5-95ae-9d4a2ed98c6e.jpg)
![survey123_windows](https://cloud.githubusercontent.com/assets/4626334/8277442/038ce656-18ed-11e5-9a29-8cc5baf132d3.png)

**Comment by survey123** [comment] 2015-06-22 18:20
Hi, could you please send your XLSForm to survey123@esri.com ? Thanks.

**Comment by esri4591** [comment] 2015-06-23 07:50
Hi, you can download it from https://drive.google.com/file/d/0By3t8IKNiDLIN2JzcnVJUnJ3QjQ/view?usp=sharing

Thanks!

**Comment by survey123** [comment] 2015-06-25 17:11
Closing this issue. Duplicate of #64 
After installing latest app all values are shown as expected.
Validated with @esri4591

**Closed by survey123** 2015-06-25 17:11 UTC
Labels: Survey123 App
