### ISSUE TITLE
Survey 123 desktop app for Windows not allowing survey downloads after install

### ISSUE THREAD

**Issue by djibo** [Esri/Survey123Community#113] opened 2015-06-03 08:49 UTC
At a workshop we had 20 participants download and install S123 for their PCs, and for each participant encountered the same problem. After logging in for the first time, they simply received a blank screen, with no option for downloading the surveys.

Here are some screen shots. For each it was the same issue.

![img_4556](https://cloud.githubusercontent.com/assets/11965622/7956128/bf7be852-09d5-11e5-95ed-d7f7cad2b22e.JPG)

![img_4566](https://cloud.githubusercontent.com/assets/11965622/7956444/dbdb911c-09d7-11e5-869a-cefe63c662a5.JPG)

**Comment by djibo** [comment] 2015-06-03 09:03
I should note as well that this happened for those with or without strong internet connections, and on people's Android phones as well.

**Comment by survey123** [comment] 2015-06-03 14:22
Hi. This happens when no surveys have been shared with the logged in user. Try the following:
1- Publish a survey
2- Create a Group in ArcGIS Online and invite other users to that group (if you are an admin use the option to add the to the group without confirmation. If you are not an admin in the organization, every user will need to manually accept the invitation to the group from ArcGIS.com)
3- In the Survey123 web site, use the sharing button to share the survey with the group you created in step 2.
4- From the Survey123 app, login and surveys will be shown in the Download Surveys gallery.

It was unfortunate that the app did not tell you anything. We should have been more explicit and tell the user that no surveys were shared with the logged in user.  We will work on this to make it more obvious.

**Comment by djibo** [comment] 2015-06-03 14:42
Thank you – a solution that I should have realized, but oddly didn't even think of! I'd added all of the users to the group, but hadn't thought to share the surveys to the group as well. For folks in a similar position I'm sure that a message explaining why there were no surveys would easily solve the problem.

**Comment by clrogers** [comment] 2015-07-07 21:35
While this did fix the problem I keep forgetting that I have to go to a completely different place to do this than in my AGO Account where the Feature Layer and the Map exist. Is there a chance that in the future we will be able to handle the sharing settings for Surveys from within our AGO Accounts especially if we are AGO Org Admins? To many locations to keep up with; one for Survey123, one for Business Analyst Online, one for AGO Accounts, one for my Esri... I'm loosing track of them all... LOL

**Comment by survey123** [comment] 2015-07-08 02:01
@clrogers Of course you can manage your Survey123 content from ArcGIS Online! 
All we are providing in the Survey123 website is a one-stop-shop for all things related to Survey123. 
However, the feature services and forms (code samples) that are used by Survey123 can also be shared in ArcGIS Online, just like any other item. :)

**Comment by clrogers** [comment] 2015-07-10 15:35
Thanks @survey123 I tried to edit the sharing in AGO but it wouldn't take for some reason so I had to do it in the Survey123 Control Panel but it worked...!!!

**Comment by markgleveque** [comment] 2015-07-24 14:36
I created two surveys, published them, and shared them with a group.  When I view the survey folder and its contents in My Content in ArcGIS Online, I can verify that the surveys are shared with the group.  Both I (the admin) and another user are members of this group.  However, when either I or the other user log into the Survey123 Mobile App, we don't see any surveys listed available for download.  Is there something else I need to do?

**Comment by survey123** [comment] 2015-07-24 15:21
@markgleveque 
Not really, nothing else you should do:
1- Publish the Survey from Connect, then in the Survey123 web site simply share the survey with the Group.  If sharing using ArcGIS.com, make sure both the Code Sample and Feature Layer items are consistently shared with the Group.
2- Make sure the users are in the Group.... and the survey will show.
If you happen to be at the Esri UC Conference in San Diego, email us at survey123@esri.com so we can get together. May be we can look closely with you at the issue and resolve it.

**Comment by clrogers** [comment] 2015-07-28 23:08
I did find that you must check the Survey123 Website and ensure that sharing is configured there to be able to see or download the survey's for some reason when they are built and uploaded into ArcGIS Online and their maps and feature layers are shared properly the survey's still do not show up for me. BUT by logging into the Survey123 Website and ensuring the sharing for the Survey(s) is set properly there they began to show up. It appears that somehow there became a disconnect between the share settings in AGO vs the Survey123 website configurations.

**Comment by markgleveque** [comment] 2015-07-29 11:28
![survey123 website permissions](https://cloud.githubusercontent.com/assets/13485164/8956382/58254a8a-35c3-11e5-8d84-ad4d0ae71796.PNG)
I have tried what @clrogers suggested and the surveys are still not showing up.  However, I noticed that I always have a mismatch between permissions that I set on the Survey123 website and in ArcGIS Online.  When I give permissions on survey to a group in ArcGIS Online and then go to the Survey123 website I don't see those permissions displayed.   Then when I apply the permissions on the Survey123 website and apply them, after I go back and view the permissions again, they revert to private, but the checkbox on the group remains checked.  Please see attached screenshot illustrating this problem.

**Comment by survey123** [comment] 2015-07-30 01:15
I would recommend using the Survey123 website to share your projects for one important reason - we have restricted the sharing settings (as demonstrated in the above screenshot) to only allow users to share with their organisation or groups.

If you set the sharing permissions in ArcGIS Online - you will get the option to make the items **public**. Survey123 will ignore all items set as shared to **public** - even if they have also been shared with groups or your organisation.

This may be the reason that some of you are unable to see your items in Survey123 on your mobile devices. Please make sure that your items are not shared to **public**.

**Comment by markgleveque** [comment] 2015-07-30 11:59
I haven't shared these as public in ArcGIS Online, so this isn't the reason why I can't see my surveys in the app.

**Comment by survey123** [comment] 2015-08-21 05:23
Closing this issue.
Just for clarity:
* We added a message in the download page to make sure folks understand when no surveys have been shared with them.
* We also addressed an issue in the iOS version of the app (v171) related to this. @markgleveque  Please open a new issue if you still see problems.

**Closed by survey123** 2015-08-21 05:23 UTC
Labels: Status - Fixed, Survey123 App

**Comment by markgleveque** [comment] 2015-08-21 11:28
I tested today and verified that I can now see the surveys on my download page on my iOS devices.  Thanks for fixing this issue.

**Comment by apaulpdx** [comment] 2015-10-13 21:21
Can surveys be SHARED via GROUPS with Org Accounts outside of your Org?

**Comment by survey123** [comment] 2015-10-14 02:26
Yes. Simply invite ArcGIS Online users from other organizations to your group. You can do this by going into your group and clicking on invite members. While you search for users, make sure you not constrain your search to users within your organization. Also please be aware that you will only see users with a public profile. By default profiles are discoverable ( public) , but they can be turned private.

**Comment by apaulpdx** [comment] 2015-10-14 14:48
![mycontent](https://cloud.githubusercontent.com/assets/4670982/10487073/16db3b82-7247-11e5-8e80-088283f20a32.JPG)
I see I wasn't super clear in my post, my apologies. I'd like to share the Code Sample with another Org. It appears that only the Feature Layer and Web Map can be shared through GROUPS. Even when I look within my own Org the GROUP does not display the Code Sample generated using Survey 123. I've attached a screen shot of my content with Sharing set to Survey 123 GROUP. Then a screen shot of that GROUP which does not have the Code Sample. Is this by design and if so can we not share Survey 123 functionality with other Orgs? 
![image](https://cloud.githubusercontent.com/assets/4670982/10487252/eabfcef4-7247-11e5-9963-7a43793b2009.png)

**Comment by apaulpdx** [comment] 2015-10-14 14:52
I see I wasn't super clear in my post, my apologies. I'd like to share the Code Sample with another Org. It appears that only the Feature Layer and Web Map can be shared through GROUPS. Even when I look within my own Org the GROUP does not display the Code Sample generated using Survey 123. I've attached a screen shot of my content with Sharing set to Survey 123 GROUP. Then a screen shot of that GROUP which does not have the Code Sample. Is this by design and if so can we not share Survey 123 functionality with other Orgs? 
![mycontent](https://cloud.githubusercontent.com/assets/4670982/10487383/8c943256-7248-11e5-8dac-6140040c50f1.JPG)
![group](https://cloud.githubusercontent.com/assets/4670982/10487395/91851d7a-7248-11e5-9e73-23d0ce54c6db.JPG)

**Comment by survey123** [comment] 2015-10-14 17:10
OK. Lets split things out.

First, you need to make sure your Survey123 form is properly shared. This is best done through the Survey123 for ArcGIS web site at  http://survey123.arcgis.com
1) Go to http://survey123.arcgis.com and login with your ArcGIS Online credentials
2) Hover your mouse over the Survey you want to share and then click on Share. 
3) Share with one or more groups
You could do all of the above directly in ArcGIS.com, but you need to make sure your Form (Code Sample) is NOT shared with everyone and that the Feature Layer and Code Sample are shared consistently (with the same groups).

Second, you need to invite members from your organization, or external organizations into your group. Note in the next screenshot that I unchecked the ' Only search for members in Survey123 for ArcGIS.'

![untitled](https://cloud.githubusercontent.com/assets/10968332/10491486/be312072-725b-11e5-87f3-0736d79b38a2.png)

**Comment by apaulpdx** [comment] 2015-10-14 17:59
Thank you for providing these instructions. Unfortunately, I've followed them exactly and still do not see Code Sample in this GROUP. All items are shared only to this GROUP but only the Map and Layer show. When I or invited members look in my GROUP should I see the Code Sample as seen in your image above? Because I've tried many times and had coworkers look over my shoulder to ensure I'm following all steps. We appreciate your help.

**Comment by apaulpdx** [comment] 2015-10-14 18:00
Thank you for providing these instructions. Unfortunately, I've followed them exactly and still do not see Code Sample in this GROUP. All items are shared only to this GROUP but only the Map and Layer show. When I or invited members look in my GROUP should we see the Code Sample as seen in your image above? Because I've tried many times and had coworkers look over my shoulder to ensure I'm following all steps. We appreciate your help.

**Comment by survey123** [comment] 2015-10-14 18:05
Try checking the Show Desktop content option on the left side as shown in this screenshot.

![untitled](https://cloud.githubusercontent.com/assets/10968332/10492918/40a2cf72-7263-11e5-922d-2ad7c6bc384b.png)

Just to be clear, whoever you invited into the Group should at this moment see the Form from the Mobile application. That is what really matters. Can people download the Form in the app? If not, again, ensure that they are in the group and that that code sample is NOT shared with everyone.

**Comment by apaulpdx** [comment] 2015-10-14 18:38
BINGO!!! As soon as I checked the Show Desktop Content it appears. Thank you again
