### ISSUE TITLE
Unexpected Token T Error Unable to create Forms with spaces in the name

### ISSUE THREAD

**Issue by Cintruenigo** [Esri/Survey123Community#54] opened 2015-04-02 20:18 UTC
I am getting this error every time I attempt to create a new Survey in Connect if the name includes a space. No space, no problem.... This used to work just fine before.

![untitled](https://cloud.githubusercontent.com/assets/1273440/6972604/c7718606-d939-11e4-97c0-010d6da4bdcc.png)

Version 1.0.59

**Comment by survey123** [comment] 2015-04-03 19:46
Looks like this issue was caused by a temporary shutdown on our servers.  Fixed now.

**Comment by survey123** [comment] 2015-04-03 22:38
@deepti10   is reporting issues on this one still. Reopening.

**Comment by mukih** [comment] 2015-05-29 09:53
I have also just experienced this problem with version 1.0.108. 
![error token t](https://cloud.githubusercontent.com/assets/4144889/7880387/e07e4a4c-05f0-11e5-98ce-bf059b3c9101.png)

**Comment by survey123** [comment] 2015-06-01 00:54
I can't reproduce this issue using Build 1.0.108 on my Windows machine, but I can reproduce it consistently on a Mac using the same build number.

@deepti10 @mukih @Cintruenigo Could you provide more information on the environments you were using to try and narrow down this issue?

**Comment by mukih** [comment] 2015-06-01 07:01
I'm using Windows 7 SP1 and have Office 2013 installed. The error happens after opening the survey123 connect in the first use. After several times and uploading XForm using the 'browse' function it stopped. Maybe try on fresh windows machine that didn't have the application installed before?

**Comment by survey123** [comment] 2015-06-09 07:04
I was able to reproduce this issue on Windows 8 today - I received the **Unexpected Token T** when creating the project _Form 1_ and the project _Form 2_, but was able to successfully convert my form when creating _Form 3_.

**Closed** 2015-07-03 05:30 UTC
Labels: Status - Fixed, Survey123 Connect, Type - Bug
