### ISSUE TITLE
Survey 123 app (iOS 9.3.2) relevant field issue

### ISSUE THREAD

**Issue by rodarter** [Esri/Survey123Community#477] opened 2016-05-26 17:05 UTC
Hello, 
I created a survey with multiple relevant fields which was working great on our iPad.  Since updating the to most recent iOS version (9.3.2), I have been having issues.  The relevant fields frequently stop working when filling out the survey (i.e. follow up question will not show up).  When this happen I have also noticed issue with a cascade select I have set up on the same form.  I tried deleting and reloading the survey, reinitialized the database in the advanced menu, deleted/reinstalled the app, and rebooted the iPad but the error is still occurring.  

The same survey works on my iPhone running (9.3.1) without the above issues.  

Thanks

**Comment by Thadius** [comment] 2016-06-01 19:14
+1

Having similar issues. Please say there is a fix soon :)

**Comment by pinpointmapping** [comment] 2016-06-09 17:44
I seem to be experiencing the same issue.  I have questions that use relevant field within a repeating question.  The form works for the first entry, but subsequent repeats don't seem to recognize the relevant field and the questions aren't shown?  Very frustrating that the survey works on desktop, but once uploaded to an iOS device with 9.3.2 it doesn't....

**Comment by Thadius** [comment] 2016-06-09 19:01
I have it working on an IPAD just not IPhone

**Comment by survey123** [comment] 2016-06-09 23:24
We are having issues reproducing this. Can you please attach your XLSForms to a comment?

**Comment by rodarter** [comment] 2016-06-09 23:36
Thanks for following up on this!  The form seems to bug out for the questions I have in the  "BMP Implementation Assessment" group (Rows 25, 33, 37, 41, 45, 50, 55, 59, 65, and 69).  If I select yes, which triggers follow up questions, without making any other changes, there is no issue.  If I deselect Yes (or re-select N/A) for these rows, then the relevant fields no longer work.  

Anyways, hope this description helps and keep up the good work! 

[Facility Inspection.xlsx](https://github.com/Esri/Survey123Community/files/308078/Facility.Inspection.xlsx)

**Comment by WarrenD56** [comment] 2016-06-13 16:26
+1 Same issue here, my survey uses relevant fields within a repeat. The first entry works fine but when the repeat is initiated for a second time fields that were required from the first entry persist despite not being visible. I've described it in greater detail on GeoNet [https://geonet.esri.com/thread/178491](url).
[Maximo Playground Survey.xlsx](https://github.com/Esri/Survey123Community/files/312262/Maximo.Playground.Survey.xlsx)

**Comment by travisbutcher** [comment] 2016-07-07 18:45
👍   We are seeing this issue in the app as well.

**Comment by survey123** [comment] 2016-07-07 23:46
Hi all. We are currently working on this problem. We were able to reproduce it. It looks like it is related to memory management changes in the latest version of iOS.  The more relevant statements you have in your survey the more  prominent the issue will be. In some cases, when you have many repeated relevant statements you may be able to create groups and apply the relevant  expression to the group instead of every question. This will help. 
The issue will take some time to be resolved. Certainly not part of our July 22 update, but we will do our best to resolve in September.

**Comment by brg234** [comment] 2016-07-11 20:06
I am also experiencing issues with iOS 9.3.2 and external selects. None of the external selects or relevancies will work on our iPad Air 2 running iOS 9.2.1 or iOS 9.3.2. Our surveys rely heavily on the ability to use cascading selects and relevancies. I hope to see this issue resolved as quickly as possible, it is very limiting to have to disable all of these features.

**Comment by survey123** [comment] 2016-07-29 22:44
@rodarter Found the problem! Will bring a  fix in our September update.
@WarrenD56  Please try version 1.6, as we cannot reproduce the problem in anymore.

**Comment by phil-wilson** [comment] 2016-08-01 03:52
Great to hear the issue has been found, also having this problem with iOS v9.3.2 and Survey123 v1.6.11 on 2 different iPads. Looking forward to the fix.

**Comment by rodarter** [comment] 2016-08-01 14:15
Excellent!  Thanks for the status update.  Looking forward to the September update.

**Comment by brg234** [comment] 2016-08-01 14:22
Glad to hear a fix has been found, looking forward to the new release! Thanks very much for your attention to this problem.

**Comment by MarlboroughDistrictCouncil** [comment] 2016-08-08 20:40
Any chance this fix can be bought forward before September?  We are using it for some emergency response forms and they are now all broken!

**Comment by survey123** [comment] 2016-09-01 17:00
Closing. Implemented in our 1.7 release.
For more information please check: https://geonet.esri.com/groups/survey123/blog/2016/09/01/international-day-against-nuclear-tests-release-17

**Closed by survey123** 2016-09-01 17:00 UTC
Labels: Status - Fixed, Survey123 App, Type - Bug
