### ISSUE TITLE
sign in to the portal arcgis dialog is obtain blank page in webview !!!

### ISSUE THREAD

**Issue by hishamshrideh** [Esri/Survey123Community#513] opened 2016-07-11 12:07 UTC
Iam try to connect the survey 123 with portal 10.4.1 with public IP , I added it to list of Arcgis portal settings in survey 123 connect , however when i click sign in  in survey the "sign in to the portal" dialog obtain blank page in webview as shown in the screenshot . please helo me ??? what is this issue ?

![sign in 2](https://cloud.githubusercontent.com/assets/17882135/16730034/32b059ac-4779-11e6-8985-0e73211870ba.png)
![sign in](https://cloud.githubusercontent.com/assets/17882135/16730035/32e5d3c0-4779-11e6-8770-e84e372db15e.png)

**Comment by survey123** [comment] 2016-07-19 01:36
Hi. This error may be caused by a self-signed https certificate in your server. Please open an Esri Tech Support case so we can get more information and can follow up with you on the issue. Thanks. Closing.

**Closed by survey123** 2016-07-19 01:36 UTC
Labels: Survey123 Connect
