### ISSUE TITLE
view fullscreen image on phone

### ISSUE THREAD

**Issue by karmstro77** [Esri/Survey123Community#190] opened 2015-09-21 15:57 UTC
I have created a field using select_one and would like the user to see sample images of the 4 different types of answers (affected, minor damage, major damage, destroyed). I have added several images to the media folder and referenced them in the choices tab of my spreadsheet next to each answer. On the desktop app, when i click on any of the images next to its appropriate checkbox, it launches a fullscreen view of the image. 
![image](https://cloud.githubusercontent.com/assets/6819070/9996862/2be25620-6057-11e5-9ca8-ae9a05152ff4.png)

However, on my iPhone, when i click on the image, nothing happens. No fullscreen view.
![image](https://cloud.githubusercontent.com/assets/6819070/9996891/50d23bc6-6057-11e5-950a-144700790089.png)

I would like the user to get a better view of the sample image. The thumbnail is too small. Is there something I am missing to get the image to display full screen?

**Comment by survey123** [comment] 2015-09-22 03:19
Thanks for your feedback!
We are flagging this as a duplicate of #169 
Expected to be fixed in the next update to the mobile app.

**Comment by survey123** [comment] 2015-09-24 22:51
Fixed on build 1.1.4. Closing.

**Closed by survey123** 2015-09-24 22:51 UTC
Labels: Status - Fixed, Survey123 App, Type - Duplicate
