### ISSUE TITLE
Support for Cascaded Selects

### ISSUE THREAD

**Issue by kengorton** [Esri/Survey123Community#53] opened 2015-04-02 19:24 UTC
In a survey I set up a field to display a cascading select such that when I select a Colombian departamento boundary (think 'states') as defined by my choice list in the choices tab of my spreadsheet, the next field should present a list of the municipios (the next lower level admin units) therein. Unfortunately no list of municipios is displayed regardless of my selection in the departamento field.

Here is the survey tab where I have the fields set up:
![survey](https://cloud.githubusercontent.com/assets/5541824/6971572/6d804d3c-d94b-11e4-84aa-2492a67782ac.JPG)
Here is the choices tab where I have the two lists defined:
![choice](https://cloud.githubusercontent.com/assets/5541824/6971583/7e9f66f2-d94b-11e4-85c0-134251248e8f.JPG)
Here is the form with 'Amazonas' selected in the Departamento field but nothing is available in the Municipio field:
![form](https://cloud.githubusercontent.com/assets/5541824/6971617/c0e56dea-d94b-11e4-902a-7e8269f7c49c.JPG)

**Comment by survey123** [comment] 2015-04-02 19:53
Thanks
Still working on this
Keep adding feedback.
Talked to Salim today. Good work spreading the word with survey123!

Ismael


On Apr 2, 2015, at 3:24 PM, "Ken Gorton" <notifications@github.com<mailto:notifications@github.com>> wrote:


In a survey I set up a field to display a cascading select such that when I select a Colombian departamento boundary (think 'states') as defined by my choice list in the choices tab of my spreadsheet, the next field should present a list of the municipios (the next lower level admin units) therein. Unfortunately no list of municipios is displayed regardless of my selection in the departamento field.

Here is the survey tab where I have the fields set up:
[survey]<https://cloud.githubusercontent.com/assets/5541824/6971572/6d804d3c-d94b-11e4-84aa-2492a67782ac.JPG>
Here is the choices tab where I have the two lists defined:
[choice]<https://cloud.githubusercontent.com/assets/5541824/6971583/7e9f66f2-d94b-11e4-85c0-134251248e8f.JPG>
Here is the form with 'Amazonas' selected in the Departamento field but nothing is available in the Municipio field:
[form]<https://cloud.githubusercontent.com/assets/5541824/6971617/c0e56dea-d94b-11e4-902a-7e8269f7c49c.JPG>

**Comment by survey123** [comment] 2015-04-02 20:04
Thanks Ken. We will look into this.

**Comment by survey123** [comment] 2015-04-02 20:33
Duplicate of #22

**Comment by stfeirer** [comment] 2015-05-05 23:20
I am looking forward to the ability to have cascading select statements in Survey123...  This will allow us to build in the option to survey species based on taxonomic categories.  For instance we may have a domain populated with all of the known species in a region and we may want to filter the list by lets say turtles, etc,

**Comment by JayW78** [comment] 2015-06-17 14:02
Yes this is needed.  Post processing is an OK work around to condense any fields but it would be extremely useful to be able to simply have a "type" and "subtype" field which could reference certain choices specified by the filter.  I am eager to have this option.

**Comment by bruceripley** [comment] 2015-07-28 01:03
+1

**Comment by Cintruenigo** [comment] 2015-07-28 01:04
Working on it as we speak Bruce! ;)

**Comment by bruceripley** [comment] 2015-07-28 01:29
Hey Ismail...

Good to hear from you, and thanks for taking the time the other day.
I'm glad I came back to say Hi.

We were debriefing today and I told the guy who works for me to submit 
some of his thoughts to the blog.

In talking with one of our senior managers I hit just a few things that 
could be snags, some of them are already on your list.
For the record here they are:

1. Performance.  Even for small surveys they take 15-30 seconds to open. 
Try Canvas... it will open a form almost immediately (there's your 
competition) .
                                 It's not that it won't work it's just 
that people expect instant results.
2. Signature.  I already told you about that.
3. Print PDF from the app.  Canvas let's you print a PDF directly from the 
app with the signature.  That's really useful if you are trying to send a 
hard copy to a contractor for example.  It also makes for  a good file 
copy, even though in the long run we are tying to make those go away.
4. Domains. Pointing to either an excel table or sql table for domain 
controlled inputs.  My example was a harvest job, again there is ONLY a 
100% chance that the user will type the name inaccurately...
5. Pages.  Your surveys go top to bottom and that may be affecting load 
time.  Canvas allows you to load "pages" or "tabs" that way the only thing 
rendering on the device is the current page.  It may reduce load times for 
you.
                     Many surveys are divided into logical sections and 
thus the "pages" make sense.

There are a few more things but I need to discuss them with some of my 
team before I put things down for you to worry about.

In the above list those are ranked in order of importance.
I left off cascading selects since you already have that.
If you want us to test something we'd be glad to, just let me know and 
I'll download it from the beta testing site.

Thanks Ismail, as always your technical sessions were well thought out and 
useful, almost never fail to learn something in them.

Take some time off... you deserve it!

Bruce

Bruce Ripley
Senior GIS Analyst
Hancock Forest Management
17700 SE Mill Plain Blvd, Suite 180
Vancouver, WA 98682
360-260-4562 (Office)
503-522-7470 (Mobile)
360-256-5474 (Fax)
bripley@hnrg.com

**Comment by martinGIS** [comment] 2015-08-05 17:51
we at E&J Gallo would like to have the cascading select statements option too!  this would make a lot more useful for in-field data collection (i.e. vineyard)
thanks Ismael and the entire team

**Comment by adismer** [comment] 2015-08-13 23:35
I agree- cascading lists are key for so many of the surveys I support.

**Comment by survey123** [comment] 2015-09-24 22:57
Closing. 
https://geonet.esri.com/groups/survey123/blog/2015/09/24/world-vegetarian-day-october-1st-update

**Closed by survey123** 2015-09-24 22:57 UTC
Labels: Status - Fixed, Survey123 Connect, Type - Enhancement
