### ISSUE TITLE
Geopoint Inside Repeat Error

### ISSUE THREAD

**Issue by bowlesgsrcx** [Esri/Survey123Community#480] opened 2016-05-31 14:28 UTC
I have added a geopoint inside a repeat for one of my surveys. The survey collects data and uploads it fine without the geopoint, but with the geopoint, I receive  the following error: Code 500 JSONArray[0] not found. I have attached both surveys for review.
Thanks,
--gary
[AboveGround_PipelineInspection.xlsx](https://github.com/Esri/Survey123Community/files/291339/AboveGround_PipelineInspection.xlsx)
[AboveGround_PipelineInspection_NOGeopoint.xlsx](https://github.com/Esri/Survey123Community/files/291342/AboveGround_PipelineInspection_NOGeopoint.xlsx)

**Comment by lmq8** [comment] 2016-06-16 13:11
I'm having this same issue as well.  I've tried rebooting and reinstalling with any luck so far.  I've created a super basic survey for testing purposes that I've attached.

Thanks,
Ian
[Geopoint Repeat.xlsx](https://github.com/Esri/Survey123Community/files/318445/Geopoint.Repeat.xlsx)

**Comment by SkeenP-NGSC** [comment] 2016-06-29 01:51
This has been a problem with me as well, now though whenever i attempt to upload a form with a point in a repeat it is throwing an error and triggering one of those annoying not responding prompts.

**Comment by survey123** [comment] 2016-06-29 01:52
Thanks all for reporting. 
We can reproduce this problem and will investigate. 
Flagging as a bug. Thanks again.

**Comment by SkeenP-NGSC** [comment] 2016-06-29 01:56
Just to note, didn't seem to have this as a problem in the beta version. Seems to be a problem on the AGOL side. Happy to provide debug logs if required.

**Comment by survey123** [comment] 2016-06-29 02:00
Agreed. It seems like the last update to ArcGIS Online may have affected this workflow. We are getting errors from Online while attempting to create the Feature Service. If you have some debug logs you would like to share, please include them as an attachment here, or simply email them to survey123@esri.com   Thanks a  lot!

**Comment by survey123** [comment] 2016-07-19 01:25
We will include a fix to this issue in our next update.  Adding to Pi Approximation day milestone.  Expect this new update to be announced via Twitter and GeoNet.
* https://geonet.esri.com/groups/survey123/blog 
* https://twitter.com/esriSurvey123

**Comment by survey123** [comment] 2016-07-26 05:45
Closing. Fix available now in the [Pi Approximation Day release](https://geonet.esri.com/groups/survey123/blog/2016/07/26/227-pi-approximation-day-release)

**Closed by survey123** 2016-07-26 05:45 UTC
Labels: Status - Fixed, Survey123 Connect, Type - Bug
