### ISSUE TITLE
Offline maps

### ISSUE THREAD

**Issue by ljaupi** [Esri/Survey123Community#187] opened 2015-09-18 21:00 UTC
it would be great to be able to have your own base maps available offline.

**Comment by survey123** [comment] 2015-09-18 23:33
Thanks for your comment. 
We will flag this enhancement request as duplicate of #114 and close.
Please feel free to add your vote to #114 
We will update status of this work in #114 
We are tentatively looking at having offline basemaps in our December 1st release.

**Closed by survey123** 2015-09-18 23:33 UTC
Labels: Survey123 App, Type - Duplicate, Type - Enhancement
